/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.Util;
import com.sun.xml.internal.ws.util.Pool;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.PropertyException;
import model.Pokoj;
import model.Gosc;
import model.CheckIn;
import model.CheckOut;

import model.ListGosc;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author HP
 */
public class FramePensjonat extends javax.swing.JFrame {

    /**
     * Creates new form FramePensjonat
     */
    public FramePensjonat() {
        initComponents();

        panelStart.setVisible(true);
        panelGoscie.setVisible(false);
        panelPokoje.setVisible(false);
        panelCheckIn.setVisible(false);
        panelCheckOut.setVisible(false);
        panelUstawienia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        buttonGoscie = new javax.swing.JButton();
        buttonPokoje = new javax.swing.JButton();
        buttonCheckIn = new javax.swing.JButton();
        buttonCheckOut = new javax.swing.JButton();
        buttonUstawienia = new javax.swing.JButton();
        buttonWyjscie = new javax.swing.JButton();
        panelStatus = new javax.swing.JPanel();
        programNazwa1 = new javax.swing.JLabel();
        programNazwa2 = new javax.swing.JLabel();
        programNazwa3 = new javax.swing.JLabel();
        programNazwa4 = new javax.swing.JLabel();
        programNazwa5 = new javax.swing.JLabel();
        programNazwa6 = new javax.swing.JLabel();
        programNazwa7 = new javax.swing.JLabel();
        programNazwa8 = new javax.swing.JLabel();
        programNazwa9 = new javax.swing.JLabel();
        programNazwa10 = new javax.swing.JLabel();
        programNazwa11 = new javax.swing.JLabel();
        panelSeparator = new javax.swing.JPanel();
        panelStart = new javax.swing.JPanel();
        programNazwa = new javax.swing.JLabel();
        programWersja = new javax.swing.JLabel();
        panelGoscie = new javax.swing.JPanel();
        buttonGoscieNowy = new javax.swing.JButton();
        panelGoscieNowy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labGoscNowyNazwisko = new javax.swing.JLabel();
        labGoscNowyPesel = new javax.swing.JLabel();
        labGoscNowyNrTelefonu = new javax.swing.JLabel();
        labGoscNowyEmail = new javax.swing.JLabel();
        insertGoscNowyNazwisko = new javax.swing.JTextField();
        insertGoscNowyImie = new javax.swing.JTextField();
        insertGoscNowyEmail = new javax.swing.JTextField();
        insertGoscNowyPesel = new javax.swing.JTextField();
        insertGoscNowyNrTelefonu = new javax.swing.JTextField();
        buttonGoscNowyXML = new javax.swing.JButton();
        labGoscNowyStatus = new javax.swing.JLabel();
        labGoscNowyStatusInfo = new javax.swing.JLabel();
        buttonGoscNowyZatwierdzSQLite = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonGoscieLista = new javax.swing.JButton();
        panelGoscieLista = new javax.swing.JPanel();
        buttonListaWczytaj = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        buttonListaWyczysc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGoscieUsun = new javax.swing.JButton();
        panelGoscieUsun = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panelPokoje = new javax.swing.JPanel();
        panelCheckIn = new javax.swing.JPanel();
        panelCheckInPostep = new javax.swing.JPanel();
        labChecInPotw = new javax.swing.JLabel();
        labChecInDane = new javax.swing.JLabel();
        labChecInPokoj = new javax.swing.JLabel();
        labChecInWydajKarte = new javax.swing.JLabel();
        buttonChecInWstecz = new javax.swing.JButton();
        buttonChecInDalej = new javax.swing.JButton();
        panelCheckInDane = new javax.swing.JPanel();
        panelCheckOut = new javax.swing.JPanel();
        panelUstawienia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonUstawieniaSQLiteWeryfikuj = new javax.swing.JButton();
        labUstawieniaStatusBazy = new javax.swing.JLabel();
        labUstawieniaStatusBazyCheck = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonUstawieniaXMLGoscieWeryfikuj = new javax.swing.JButton();
        labUstawieniaStatusBazy1 = new javax.swing.JLabel();
        labUstawieniaStatusXMLGoscieCheck = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        labUstawieniaStatusBazy2 = new javax.swing.JLabel();
        labUstawieniaStatusXMLPokojeCheck = new javax.swing.JLabel();
        buttonUstawieniaXMLPokojeWeryfikuj = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        buttonUstawieniaXMLGoscieNowy = new javax.swing.JButton();
        buttonUstawieniaXMLPokojeNowy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(204, 102, 0));

        imgLogo.setBackground(new java.awt.Color(255, 255, 255));
        imgLogo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoPensjonat2.png"))); // NOI18N
        imgLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLogoMouseClicked(evt);
            }
        });

        buttonGoscie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonGoscie.setText("Goście");
        buttonGoscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoscieActionPerformed(evt);
            }
        });

        buttonPokoje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonPokoje.setText("Pokoje");
        buttonPokoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPokojeActionPerformed(evt);
            }
        });

        buttonCheckIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCheckIn.setText("Check-In");
        buttonCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckInActionPerformed(evt);
            }
        });

        buttonCheckOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCheckOut.setText("Check-Out");
        buttonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckOutActionPerformed(evt);
            }
        });

        buttonUstawienia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonUstawienia.setText("Ustawienia");
        buttonUstawienia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUstawieniaActionPerformed(evt);
            }
        });

        buttonWyjscie.setText("Wyjście");
        buttonWyjscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWyjscieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonWyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(imgLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonGoscie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPokoje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonUstawienia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(buttonGoscie, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPokoje, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonUstawienia, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(buttonWyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelStatus.setBackground(new java.awt.Color(255, 204, 51));

        programNazwa1.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa1.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa1.setText("Zakwaterownych gości w pokojach:");

        programNazwa2.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        programNazwa2.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa2.setText("Licencja dla:");

        programNazwa3.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa3.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa3.setText("Zajętych łóżek:");

        programNazwa4.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa4.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa4.setText(".........");

        programNazwa5.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa5.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa5.setText(".........");

        programNazwa6.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa6.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa6.setText("z");

        programNazwa7.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa7.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa7.setText(".........");

        programNazwa8.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa8.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa8.setText(".........");

        programNazwa9.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programNazwa9.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programNazwa9.setText("z");

        programNazwa10.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        programNazwa10.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa10.setText("Statystyki:");

        programNazwa11.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        programNazwa11.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        programNazwa11.setText("Borowy Dwór BS&F");

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStatusLayout.createSequentialGroup()
                        .addComponent(programNazwa10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(programNazwa2))
                    .addGroup(panelStatusLayout.createSequentialGroup()
                        .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programNazwa1)
                            .addComponent(programNazwa3))
                        .addGap(37, 37, 37)
                        .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelStatusLayout.createSequentialGroup()
                                .addComponent(programNazwa4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(programNazwa6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelStatusLayout.createSequentialGroup()
                                .addComponent(programNazwa7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(programNazwa9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programNazwa8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programNazwa5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(programNazwa11)))
                .addGap(28, 28, 28))
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStatusLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(programNazwa10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(programNazwa2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStatusLayout.createSequentialGroup()
                        .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(programNazwa1)
                            .addComponent(programNazwa4)
                            .addComponent(programNazwa5)
                            .addComponent(programNazwa6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(programNazwa3)
                            .addComponent(programNazwa7)
                            .addComponent(programNazwa8)
                            .addComponent(programNazwa9)))
                    .addComponent(programNazwa11))
                .addGap(13, 13, 13))
        );

        panelSeparator.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout panelSeparatorLayout = new javax.swing.GroupLayout(panelSeparator);
        panelSeparator.setLayout(panelSeparatorLayout);
        panelSeparatorLayout.setHorizontalGroup(
            panelSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSeparatorLayout.setVerticalGroup(
            panelSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        panelStart.setBackground(new java.awt.Color(102, 102, 102));

        programNazwa.setBackground(new java.awt.Color(255, 255, 255));
        programNazwa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        programNazwa.setForeground(new java.awt.Color(255, 255, 255));
        programNazwa.setText("Pensjonat Lite");

        programWersja.setBackground(new java.awt.Color(255, 255, 255));
        programWersja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programWersja.setForeground(new java.awt.Color(255, 255, 255));
        programWersja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        programWersja.setText("v. 1.180428");

        javax.swing.GroupLayout panelStartLayout = new javax.swing.GroupLayout(panelStart);
        panelStart.setLayout(panelStartLayout);
        panelStartLayout.setHorizontalGroup(
            panelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStartLayout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addGroup(panelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(programWersja)
                    .addComponent(programNazwa))
                .addGap(295, 295, 295))
        );
        panelStartLayout.setVerticalGroup(
            panelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStartLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(programNazwa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programWersja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGoscie.setBackground(new java.awt.Color(204, 204, 204));

        buttonGoscieNowy.setText("Nowy Gość");
        buttonGoscieNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoscieNowyActionPerformed(evt);
            }
        });

        panelGoscieNowy.setPreferredSize(new java.awt.Dimension(600, 530));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Imię:");

        labGoscNowyNazwisko.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labGoscNowyNazwisko.setText("Nazwisko:");

        labGoscNowyPesel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labGoscNowyPesel.setText("PESEL:");

        labGoscNowyNrTelefonu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labGoscNowyNrTelefonu.setText("Nr telefonu:");

        labGoscNowyEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labGoscNowyEmail.setText("Email:");

        insertGoscNowyNazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGoscNowyNazwiskoActionPerformed(evt);
            }
        });

        insertGoscNowyImie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGoscNowyImieActionPerformed(evt);
            }
        });

        insertGoscNowyEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGoscNowyEmailActionPerformed(evt);
            }
        });

        insertGoscNowyPesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGoscNowyPeselActionPerformed(evt);
            }
        });

        insertGoscNowyNrTelefonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertGoscNowyNrTelefonuActionPerformed(evt);
            }
        });

        buttonGoscNowyXML.setText("XML");
        buttonGoscNowyXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoscNowyXMLActionPerformed(evt);
            }
        });

        labGoscNowyStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labGoscNowyStatus.setText("Status:");

        labGoscNowyStatusInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labGoscNowyStatusInfo.setForeground(new java.awt.Color(102, 102, 102));
        labGoscNowyStatusInfo.setText("wprowadź dane");

        buttonGoscNowyZatwierdzSQLite.setText("ZAPISZ do Bazy Danych");
        buttonGoscNowyZatwierdzSQLite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoscNowyZatwierdzSQLiteActionPerformed(evt);
            }
        });

        jButton1.setText("Wyczyść");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGoscieNowyLayout = new javax.swing.GroupLayout(panelGoscieNowy);
        panelGoscieNowy.setLayout(panelGoscieNowyLayout);
        panelGoscieNowyLayout.setHorizontalGroup(
            panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoscieNowyLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertGoscNowyPesel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertGoscNowyImie, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labGoscNowyPesel)
                    .addGroup(panelGoscieNowyLayout.createSequentialGroup()
                        .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertGoscNowyNrTelefonu, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labGoscNowyNrTelefonu)
                            .addComponent(labGoscNowyStatus)
                            .addComponent(labGoscNowyStatusInfo)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertGoscNowyNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labGoscNowyEmail)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGoscieNowyLayout.createSequentialGroup()
                                    .addComponent(buttonGoscNowyXML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(insertGoscNowyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonGoscNowyZatwierdzSQLite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labGoscNowyNazwisko))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        panelGoscieNowyLayout.setVerticalGroup(
            panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoscieNowyLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labGoscNowyNazwisko))
                .addGap(11, 11, 11)
                .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertGoscNowyNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertGoscNowyImie, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(labGoscNowyPesel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelGoscieNowyLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(labGoscNowyEmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGoscieNowyLayout.createSequentialGroup()
                        .addComponent(insertGoscNowyPesel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labGoscNowyNrTelefonu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertGoscNowyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertGoscNowyNrTelefonu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(buttonGoscNowyZatwierdzSQLite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGoscieNowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGoscNowyXML, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addGroup(panelGoscieNowyLayout.createSequentialGroup()
                        .addComponent(labGoscNowyStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labGoscNowyStatusInfo)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        buttonGoscieLista.setText("Lista gości");
        buttonGoscieLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoscieListaActionPerformed(evt);
            }
        });

        panelGoscieLista.setPreferredSize(new java.awt.Dimension(600, 530));

        buttonListaWczytaj.setText("Wczytaj aktualną listę");
        buttonListaWczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListaWczytajActionPerformed(evt);
            }
        });

        jButton3.setText("Dodaj");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Lista Gości:");

        jButton6.setText("Usuń ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Przekwateruj");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buttonListaWyczysc.setText("Wyczyść widok");
        buttonListaWyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListaWyczyscActionPerformed(evt);
            }
        });

        javax.swing.table.DefaultTableModel model =
        new javax.swing.table.DefaultTableModel(

            new String [] {
                "ID", "Imię", "Nazwisko", "PESEL", "Nr tel.", "Email"
            }, 0
        );
        jTable1.setModel(model);

        for (Gosc g : dbc.selectGosc() ) {

            model.addRow(
                new Object[]{

                    g.getId(), g.getImie(), g.getNazwisko(),
                    g.getPesel(), g.getNrTelefonu(), g.getEmail()

                }

            );
        }
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout panelGoscieListaLayout = new javax.swing.GroupLayout(panelGoscieLista);
        panelGoscieLista.setLayout(panelGoscieListaLayout);
        panelGoscieListaLayout.setHorizontalGroup(
            panelGoscieListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoscieListaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelGoscieListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGoscieListaLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGoscieListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelGoscieListaLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonListaWyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonListaWczytaj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelGoscieListaLayout.setVerticalGroup(
            panelGoscieListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoscieListaLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(panelGoscieListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonListaWczytaj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonListaWyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGoscieListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        buttonGoscieUsun.setText("Usuń Gościa");
        buttonGoscieUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoscieUsunActionPerformed(evt);
            }
        });

        jLabel8.setText("Imię:");

        jTextField1.setText("jTextField1");

        jLabel9.setText("Nazwisko:");

        jTextField2.setText("jTextField2");

        jLabel10.setText("PESEL:");

        jTextField3.setText("jTextField2");

        jLabel11.setText("Nr telefonu:");

        jTextField4.setText("jTextField2");

        jLabel12.setText("Email:");

        jTextField5.setText("jTextField2");

        jButton4.setText("Szukaj");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Wyszukaj Gościa:");

        jButton5.setText("Usuń");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout panelGoscieUsunLayout = new javax.swing.GroupLayout(panelGoscieUsun);
        panelGoscieUsun.setLayout(panelGoscieUsunLayout);
        panelGoscieUsunLayout.setHorizontalGroup(
            panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoscieUsunLayout.createSequentialGroup()
                .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelGoscieUsunLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelGoscieUsunLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGap(22, 22, 22)
                            .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelGoscieUsunLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jTextField4))))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelGoscieUsunLayout.setVerticalGroup(
            panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGoscieUsunLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGoscieUsunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout panelGoscieLayout = new javax.swing.GroupLayout(panelGoscie);
        panelGoscie.setLayout(panelGoscieLayout);
        panelGoscieLayout.setHorizontalGroup(
            panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGoscieLayout.createSequentialGroup()
                .addGroup(panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGoscieLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonGoscieLista, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonGoscieUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGoscieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonGoscieNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGoscieNowy, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
            .addGroup(panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGoscieLayout.createSequentialGroup()
                    .addGap(0, 175, Short.MAX_VALUE)
                    .addComponent(panelGoscieLista, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)))
            .addGroup(panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGoscieLayout.createSequentialGroup()
                    .addGap(0, 175, Short.MAX_VALUE)
                    .addComponent(panelGoscieUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelGoscieLayout.setVerticalGroup(
            panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGoscieNowy, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
            .addGroup(panelGoscieLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(buttonGoscieNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGoscieLista, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonGoscieUsun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGoscieLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
            .addGroup(panelGoscieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGoscieUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPokojeLayout = new javax.swing.GroupLayout(panelPokoje);
        panelPokoje.setLayout(panelPokojeLayout);
        panelPokojeLayout.setHorizontalGroup(
            panelPokojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        panelPokojeLayout.setVerticalGroup(
            panelPokojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        panelCheckInPostep.setBackground(new java.awt.Color(255, 204, 0));

        labChecInPotw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labChecInPotw.setText("Potwierdzenie");

        labChecInDane.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labChecInDane.setText("Dane osobowe");

        labChecInPokoj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labChecInPokoj.setText("Wybierz pokój");

        labChecInWydajKarte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labChecInWydajKarte.setText("Wydaj kartę");

        buttonChecInWstecz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonChecInWstecz.setText("<- Wstecz");
        buttonChecInWstecz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChecInWsteczActionPerformed(evt);
            }
        });

        buttonChecInDalej.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonChecInDalej.setText("Dalej ->");
        buttonChecInDalej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChecInDalejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCheckInPostepLayout = new javax.swing.GroupLayout(panelCheckInPostep);
        panelCheckInPostep.setLayout(panelCheckInPostepLayout);
        panelCheckInPostepLayout.setHorizontalGroup(
            panelCheckInPostepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCheckInPostepLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonChecInWstecz, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(labChecInDane, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labChecInPokoj)
                .addGap(30, 30, 30)
                .addComponent(labChecInWydajKarte, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labChecInPotw)
                .addGap(18, 18, 18)
                .addComponent(buttonChecInDalej, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCheckInPostepLayout.setVerticalGroup(
            panelCheckInPostepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckInPostepLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCheckInPostepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChecInDalej, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labChecInDane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labChecInPokoj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labChecInWydajKarte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labChecInPotw)
                    .addComponent(buttonChecInWstecz, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCheckInDaneLayout = new javax.swing.GroupLayout(panelCheckInDane);
        panelCheckInDane.setLayout(panelCheckInDaneLayout);
        panelCheckInDaneLayout.setHorizontalGroup(
            panelCheckInDaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        panelCheckInDaneLayout.setVerticalGroup(
            panelCheckInDaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCheckInLayout = new javax.swing.GroupLayout(panelCheckIn);
        panelCheckIn.setLayout(panelCheckInLayout);
        panelCheckInLayout.setHorizontalGroup(
            panelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCheckInDane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelCheckInPostep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCheckInLayout.setVerticalGroup(
            panelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckInLayout.createSequentialGroup()
                .addComponent(panelCheckInDane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
            .addGroup(panelCheckInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCheckInLayout.createSequentialGroup()
                    .addGap(0, 454, Short.MAX_VALUE)
                    .addComponent(panelCheckInPostep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panelCheckOutLayout = new javax.swing.GroupLayout(panelCheckOut);
        panelCheckOut.setLayout(panelCheckOutLayout);
        panelCheckOutLayout.setHorizontalGroup(
            panelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        panelCheckOutLayout.setVerticalGroup(
            panelCheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lokalizacja pliku z Bazą Danych SQLite:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("C:\\\\Users\\\\HP\\\\Documents\\\\NetBeansProjects\\\\Pensjonat\\\\src\\\\database\\\\pensjonat.db");

        buttonUstawieniaSQLiteWeryfikuj.setText("Weryfikuj SQLite");
        buttonUstawieniaSQLiteWeryfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUstawieniaSQLiteWeryfikujActionPerformed(evt);
            }
        });

        labUstawieniaStatusBazy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labUstawieniaStatusBazy.setText("Status Bazy Danych:");

        labUstawieniaStatusBazyCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labUstawieniaStatusBazyCheck.setForeground(new java.awt.Color(153, 153, 153));
        labUstawieniaStatusBazyCheck.setText("<kliknij Weryfikuj>");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Lokalizacja pliku z Bazą Danych XML o Pokojach");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("C:\\\\Users\\\\HP\\\\Documents\\\\NetBeansProjects\\\\Pensjonat\\\\src\\\\database\\\\bazaXMLpokoje.xml");

        buttonUstawieniaXMLGoscieWeryfikuj.setText("Weryfikuj XML");
        buttonUstawieniaXMLGoscieWeryfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUstawieniaXMLGoscieWeryfikujActionPerformed(evt);
            }
        });

        labUstawieniaStatusBazy1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labUstawieniaStatusBazy1.setText("Status Bazy Danych:");

        labUstawieniaStatusXMLGoscieCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labUstawieniaStatusXMLGoscieCheck.setForeground(new java.awt.Color(153, 153, 153));
        labUstawieniaStatusXMLGoscieCheck.setText("<kliknij Weryfikuj>");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Lokalizacja pliku XML z informacją o nowym Gościu:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("C:\\\\Users\\\\HP\\\\Documents\\\\NetBeansProjects\\\\Pensjonat\\\\src\\\\database\\\\nowyGoscXML.xml");

        labUstawieniaStatusBazy2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labUstawieniaStatusBazy2.setText("Status Bazy Danych:");

        labUstawieniaStatusXMLPokojeCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labUstawieniaStatusXMLPokojeCheck.setForeground(new java.awt.Color(153, 153, 153));
        labUstawieniaStatusXMLPokojeCheck.setText("<kliknij Weryfikuj>");

        buttonUstawieniaXMLPokojeWeryfikuj.setText("Weryfikuj XML");
        buttonUstawieniaXMLPokojeWeryfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUstawieniaXMLPokojeWeryfikujActionPerformed(evt);
            }
        });

        buttonUstawieniaXMLGoscieNowy.setText("Utwórz nowy plik");
        buttonUstawieniaXMLGoscieNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUstawieniaXMLGoscieNowyActionPerformed(evt);
            }
        });

        buttonUstawieniaXMLPokojeNowy.setText("Utwórz nowy plik");
        buttonUstawieniaXMLPokojeNowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUstawieniaXMLPokojeNowyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUstawieniaLayout = new javax.swing.GroupLayout(panelUstawienia);
        panelUstawienia.setLayout(panelUstawieniaLayout);
        panelUstawieniaLayout.setHorizontalGroup(
            panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUstawieniaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(panelUstawieniaLayout.createSequentialGroup()
                        .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUstawieniaLayout.createSequentialGroup()
                                .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labUstawieniaStatusBazy2)
                                    .addComponent(labUstawieniaStatusXMLPokojeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonUstawieniaXMLPokojeWeryfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonUstawieniaXMLPokojeNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelUstawieniaLayout.createSequentialGroup()
                                .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labUstawieniaStatusBazy)
                                    .addComponent(labUstawieniaStatusBazyCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(buttonUstawieniaSQLiteWeryfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUstawieniaLayout.createSequentialGroup()
                                .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labUstawieniaStatusBazy1)
                                    .addComponent(labUstawieniaStatusXMLGoscieCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(buttonUstawieniaXMLGoscieWeryfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonUstawieniaXMLGoscieNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelUstawieniaLayout.setVerticalGroup(
            panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUstawieniaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUstawieniaLayout.createSequentialGroup()
                        .addComponent(labUstawieniaStatusBazy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labUstawieniaStatusBazyCheck))
                    .addComponent(buttonUstawieniaSQLiteWeryfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUstawieniaLayout.createSequentialGroup()
                        .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUstawieniaLayout.createSequentialGroup()
                                .addComponent(labUstawieniaStatusBazy1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labUstawieniaStatusXMLGoscieCheck))
                            .addComponent(buttonUstawieniaXMLGoscieWeryfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUstawieniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonUstawieniaXMLPokojeWeryfikuj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonUstawieniaXMLPokojeNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUstawieniaLayout.createSequentialGroup()
                                .addComponent(labUstawieniaStatusBazy2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labUstawieniaStatusXMLPokojeCheck)))
                        .addGap(34, 34, 34))
                    .addGroup(panelUstawieniaLayout.createSequentialGroup()
                        .addComponent(buttonUstawieniaXMLGoscieNowy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 325, Short.MAX_VALUE)
                    .addComponent(panelGoscie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 344, Short.MAX_VALUE)
                    .addComponent(panelPokoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 344, Short.MAX_VALUE)
                    .addComponent(panelCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 344, Short.MAX_VALUE)
                    .addComponent(panelCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 347, Short.MAX_VALUE)
                    .addComponent(panelUstawienia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 157, Short.MAX_VALUE)
                    .addComponent(panelGoscie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 168, Short.MAX_VALUE)
                    .addComponent(panelPokoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 159, Short.MAX_VALUE)
                    .addComponent(panelCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 167, Short.MAX_VALUE)
                    .addComponent(panelCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 170, Short.MAX_VALUE)
                    .addComponent(panelUstawienia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseClicked
        // TODO add your handling code here:

        panelStart.setVisible(true);
        panelGoscie.setVisible(false);
        panelPokoje.setVisible(false);
        panelCheckIn.setVisible(false);
        panelCheckOut.setVisible(false);
        panelUstawienia.setVisible(false);

    }//GEN-LAST:event_imgLogoMouseClicked

    private void insertGoscNowyImieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGoscNowyImieActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_insertGoscNowyImieActionPerformed

    private void buttonGoscieNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoscieNowyActionPerformed
        // TODO add your handling code here:

        panelGoscieNowy.setVisible(true);
        panelGoscieLista.setVisible(false);
        panelGoscieUsun.setVisible(false);

    }//GEN-LAST:event_buttonGoscieNowyActionPerformed

    private void buttonGoscieListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoscieListaActionPerformed
        // TODO add your handling code here:

        panelGoscieNowy.setVisible(false);
        panelGoscieLista.setVisible(true);
        panelGoscieUsun.setVisible(false);

    }//GEN-LAST:event_buttonGoscieListaActionPerformed

    private void buttonGoscieUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoscieUsunActionPerformed
        // TODO add your handling code here:

        panelGoscieNowy.setVisible(false);
        panelGoscieLista.setVisible(false);
        panelGoscieUsun.setVisible(true);


    }//GEN-LAST:event_buttonGoscieUsunActionPerformed

    private void buttonGoscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoscieActionPerformed
        // TODO add your handling code here:

        panelStart.setVisible(false);
        panelGoscie.setVisible(true);
        panelPokoje.setVisible(false);
        panelCheckIn.setVisible(false);
        panelCheckOut.setVisible(false);
        panelUstawienia.setVisible(false);


    }//GEN-LAST:event_buttonGoscieActionPerformed

    private void buttonPokojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPokojeActionPerformed
        // TODO add your handling code here:

        panelStart.setVisible(false);
        panelGoscie.setVisible(false);
        panelPokoje.setVisible(true);
        panelCheckIn.setVisible(false);
        panelCheckOut.setVisible(false);
        panelUstawienia.setVisible(false);

    }//GEN-LAST:event_buttonPokojeActionPerformed

    private void buttonCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckInActionPerformed
        // TODO add your handling code here:

        panelStart.setVisible(false);
        panelGoscie.setVisible(false);
        panelPokoje.setVisible(false);
        panelCheckIn.setVisible(true);
        panelCheckOut.setVisible(false);
        panelUstawienia.setVisible(false);
    }//GEN-LAST:event_buttonCheckInActionPerformed

    private void buttonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckOutActionPerformed
        // TODO add your handling code here:

        panelStart.setVisible(false);
        panelGoscie.setVisible(false);
        panelPokoje.setVisible(false);
        panelCheckIn.setVisible(false);
        panelCheckOut.setVisible(true);
        panelUstawienia.setVisible(false);
    }//GEN-LAST:event_buttonCheckOutActionPerformed

    private void buttonUstawieniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUstawieniaActionPerformed
        // TODO add your handling code here:

        panelStart.setVisible(false);
        panelGoscie.setVisible(false);
        panelPokoje.setVisible(false);
        panelCheckIn.setVisible(false);
        panelCheckOut.setVisible(false);
        panelUstawienia.setVisible(true);

    }//GEN-LAST:event_buttonUstawieniaActionPerformed

    private void buttonUstawieniaSQLiteWeryfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUstawieniaSQLiteWeryfikujActionPerformed
        // TODO add your handling code here:

        File bazadanych = new File("C:\\Users\\HP\\Documents\\NetBeansProjects\\Pensjonat\\src\\database\\pensjonat.db");
        if (bazadanych.exists() == true) {
            labUstawieniaStatusBazyCheck.setForeground(new java.awt.Color(0, 200, 0));
            labUstawieniaStatusBazyCheck.setText("Wykryto plik bazy danych!");
        } else {
            labUstawieniaStatusBazyCheck.setForeground(Color.RED);
            labUstawieniaStatusBazyCheck.setText("Brak pliku bazy danych!");

        }


    }//GEN-LAST:event_buttonUstawieniaSQLiteWeryfikujActionPerformed

    private void buttonChecInDalejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChecInDalejActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonChecInDalejActionPerformed

    private void buttonChecInWsteczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChecInWsteczActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonChecInWsteczActionPerformed

    private void buttonGoscNowyXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoscNowyXMLActionPerformed
        // TODO add your handling code here:

        String nowyGoscImie = insertGoscNowyImie.getText();
        String nowyGoscNazwisko = insertGoscNowyNazwisko.getText();
        String nowyGoscPesel = insertGoscNowyPesel.getText();
        String nowyGoscNrTelefonu = insertGoscNowyNrTelefonu.getText();
        String nowyGoscEmail = insertGoscNowyEmail.getText();

        if (nowyGoscImie.isEmpty()
                | nowyGoscNazwisko.isEmpty()
                | nowyGoscPesel.isEmpty()
                | nowyGoscNrTelefonu.isEmpty()
                | nowyGoscEmail.isEmpty()) {

            labGoscNowyStatusInfo.setText("Puste pole!");
            labGoscNowyStatusInfo.setForeground(Color.red);
        } else {

            GoscNowyXML.dodajGosciaXML(
                    nowyGoscImie,
                    nowyGoscNazwisko,
                    nowyGoscPesel,
                    nowyGoscNrTelefonu,
                    nowyGoscEmail);

            labGoscNowyStatusInfo.setText("Zapisano XML!");
            labGoscNowyStatusInfo.setForeground(new java.awt.Color(0, 200, 0));
            

        }


    }//GEN-LAST:event_buttonGoscNowyXMLActionPerformed


    private void buttonUstawieniaXMLGoscieWeryfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUstawieniaXMLGoscieWeryfikujActionPerformed
        // TODO add your handling code here:

        File bazaXMLgoscie = new File("C:\\Users\\HP\\Documents\\NetBeansProjects\\Pensjonat\\src\\database\\bazaXMLgoscie.xml");
        if (bazaXMLgoscie.isFile() == true) {
            labUstawieniaStatusXMLGoscieCheck.setForeground(new java.awt.Color(0, 200, 0));
            labUstawieniaStatusXMLGoscieCheck.setText("Plik XML istnieje!");
        } else {
            labUstawieniaStatusXMLGoscieCheck.setForeground(Color.RED);
            labUstawieniaStatusXMLGoscieCheck.setText("Brak pliku XML!");
        }


    }//GEN-LAST:event_buttonUstawieniaXMLGoscieWeryfikujActionPerformed

    private void buttonUstawieniaXMLPokojeWeryfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUstawieniaXMLPokojeWeryfikujActionPerformed
        // TODO add your handling code here:

        File bazaXMLpokoje = new File("C:\\Users\\HP\\Documents\\NetBeansProjects\\Pensjonat\\src\\database\\bazaXMLpokoje.xml");
        if (bazaXMLpokoje.isFile() == true) {
            labUstawieniaStatusXMLPokojeCheck.setForeground(new java.awt.Color(0, 200, 0));
            labUstawieniaStatusXMLPokojeCheck.setText("Plik XML istnieje!");
        } else {
            labUstawieniaStatusXMLPokojeCheck.setForeground(Color.RED);
            labUstawieniaStatusXMLPokojeCheck.setText("Brak pliku XML!");
        }


    }//GEN-LAST:event_buttonUstawieniaXMLPokojeWeryfikujActionPerformed

    private void buttonUstawieniaXMLGoscieNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUstawieniaXMLGoscieNowyActionPerformed
        // TODO add your handling code here:

        File bazaXMLgoscie = new File("C:\\Users\\HP\\Documents\\NetBeansProjects\\Pensjonat\\src\\database\\nowyGoscXML.xml");
        if (bazaXMLgoscie.isFile() == false) {
            try {
                bazaXMLgoscie.createNewFile();
                labUstawieniaStatusXMLGoscieCheck.setText("Utworzono nowy plik!");
                labUstawieniaStatusXMLGoscieCheck.setForeground(Color.YELLOW);
            } catch (IOException ex) {
                Logger.getLogger(FramePensjonat.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            labUstawieniaStatusXMLGoscieCheck.setText("Plik prawdopodobnie już istnieje.");
            labUstawieniaStatusXMLGoscieCheck.setForeground(Color.ORANGE);
        }


    }//GEN-LAST:event_buttonUstawieniaXMLGoscieNowyActionPerformed

    private void buttonUstawieniaXMLPokojeNowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUstawieniaXMLPokojeNowyActionPerformed
        // TODO add your handling code here:

        File bazaXMLpokoje = new File("C:\\Users\\HP\\Documents\\NetBeansProjects\\Pensjonat\\src\\database\\bazaXMLpokoje.xml");
        if (bazaXMLpokoje.isFile() == false) {
            try {
                bazaXMLpokoje.createNewFile();
                labUstawieniaStatusXMLPokojeCheck.setText("Utworzono nowy plik!");
                labUstawieniaStatusXMLPokojeCheck.setForeground(Color.YELLOW);
            } catch (IOException ex) {
                Logger.getLogger(FramePensjonat.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            labUstawieniaStatusXMLPokojeCheck.setText("Plik prawdopodobnie już istnieje.");
            labUstawieniaStatusXMLPokojeCheck.setForeground(Color.ORANGE);
        }


    }//GEN-LAST:event_buttonUstawieniaXMLPokojeNowyActionPerformed

    private void buttonWyjscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWyjscieActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_buttonWyjscieActionPerformed

    private void insertGoscNowyNazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGoscNowyNazwiskoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_insertGoscNowyNazwiskoActionPerformed

    private void insertGoscNowyPeselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGoscNowyPeselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertGoscNowyPeselActionPerformed

    private void insertGoscNowyNrTelefonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGoscNowyNrTelefonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertGoscNowyNrTelefonuActionPerformed

    private void insertGoscNowyEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertGoscNowyEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertGoscNowyEmailActionPerformed

    private void buttonGoscNowyZatwierdzSQLiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoscNowyZatwierdzSQLiteActionPerformed
        // TODO add your handling code here:

        String nowyGoscImie = insertGoscNowyImie.getText();
        String nowyGoscNazwisko = insertGoscNowyNazwisko.getText();
        String nowyGoscPesel = insertGoscNowyPesel.getText();
        String nowyGoscNrTelefonu = insertGoscNowyNrTelefonu.getText();
        String nowyGoscEmail = insertGoscNowyEmail.getText();

        DBConnect pensjonat = new DBConnect();

        if (nowyGoscImie.isEmpty()
                | nowyGoscNazwisko.isEmpty()
                | nowyGoscPesel.isEmpty()
                | nowyGoscNrTelefonu.isEmpty()
                | nowyGoscEmail.isEmpty()) {

            labGoscNowyStatusInfo.setText("Puste pole!");
            labGoscNowyStatusInfo.setForeground(Color.red);
        } else {

            pensjonat.insertGosc(nowyGoscImie, nowyGoscNazwisko, nowyGoscPesel, nowyGoscNrTelefonu, nowyGoscEmail);

            labGoscNowyStatusInfo.setText("Zapisano SQL!");
            labGoscNowyStatusInfo.setForeground(new java.awt.Color(0, 200, 0));
            

        }

    }//GEN-LAST:event_buttonGoscNowyZatwierdzSQLiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

            labGoscNowyStatusInfo.setText("wprowadź dane");
            labGoscNowyStatusInfo.setForeground(Color.GRAY);
            
            insertGoscNowyImie.setText("");
            insertGoscNowyNazwisko.setText("");
            insertGoscNowyPesel.setText("");
            insertGoscNowyNrTelefonu.setText("");
            insertGoscNowyEmail.setText("");




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void buttonListaWczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListaWczytajActionPerformed
        // TODO add your handling code here:
        

        
        
        
    }//GEN-LAST:event_buttonListaWczytajActionPerformed

    private void buttonListaWyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListaWyczyscActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_buttonListaWyczyscActionPerformed

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePensjonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePensjonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePensjonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePensjonat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FramePensjonat().setVisible(true);
            }
        });


        
          
    }


private DBConnect dbc = new DBConnect();
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChecInDalej;
    private javax.swing.JButton buttonChecInWstecz;
    private javax.swing.JButton buttonCheckIn;
    private javax.swing.JButton buttonCheckOut;
    private javax.swing.JButton buttonGoscNowyXML;
    private javax.swing.JButton buttonGoscNowyZatwierdzSQLite;
    private javax.swing.JButton buttonGoscie;
    private javax.swing.JButton buttonGoscieLista;
    private javax.swing.JButton buttonGoscieNowy;
    private javax.swing.JButton buttonGoscieUsun;
    private javax.swing.JButton buttonListaWczytaj;
    private javax.swing.JButton buttonListaWyczysc;
    private javax.swing.JButton buttonPokoje;
    private javax.swing.JButton buttonUstawienia;
    private javax.swing.JButton buttonUstawieniaSQLiteWeryfikuj;
    private javax.swing.JButton buttonUstawieniaXMLGoscieNowy;
    private javax.swing.JButton buttonUstawieniaXMLGoscieWeryfikuj;
    private javax.swing.JButton buttonUstawieniaXMLPokojeNowy;
    private javax.swing.JButton buttonUstawieniaXMLPokojeWeryfikuj;
    private javax.swing.JButton buttonWyjscie;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JTextField insertGoscNowyEmail;
    private javax.swing.JTextField insertGoscNowyImie;
    private javax.swing.JTextField insertGoscNowyNazwisko;
    private javax.swing.JTextField insertGoscNowyNrTelefonu;
    private javax.swing.JTextField insertGoscNowyPesel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel labChecInDane;
    private javax.swing.JLabel labChecInPokoj;
    private javax.swing.JLabel labChecInPotw;
    private javax.swing.JLabel labChecInWydajKarte;
    private javax.swing.JLabel labGoscNowyEmail;
    private javax.swing.JLabel labGoscNowyNazwisko;
    private javax.swing.JLabel labGoscNowyNrTelefonu;
    private javax.swing.JLabel labGoscNowyPesel;
    private javax.swing.JLabel labGoscNowyStatus;
    private javax.swing.JLabel labGoscNowyStatusInfo;
    private javax.swing.JLabel labUstawieniaStatusBazy;
    private javax.swing.JLabel labUstawieniaStatusBazy1;
    private javax.swing.JLabel labUstawieniaStatusBazy2;
    private javax.swing.JLabel labUstawieniaStatusBazyCheck;
    private javax.swing.JLabel labUstawieniaStatusXMLGoscieCheck;
    private javax.swing.JLabel labUstawieniaStatusXMLPokojeCheck;
    private javax.swing.JPanel panelCheckIn;
    private javax.swing.JPanel panelCheckInDane;
    private javax.swing.JPanel panelCheckInPostep;
    private javax.swing.JPanel panelCheckOut;
    private javax.swing.JPanel panelGoscie;
    private javax.swing.JPanel panelGoscieLista;
    private javax.swing.JPanel panelGoscieNowy;
    private javax.swing.JPanel panelGoscieUsun;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPokoje;
    private javax.swing.JPanel panelSeparator;
    private javax.swing.JPanel panelStart;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JPanel panelUstawienia;
    private javax.swing.JLabel programNazwa;
    private javax.swing.JLabel programNazwa1;
    private javax.swing.JLabel programNazwa10;
    private javax.swing.JLabel programNazwa11;
    private javax.swing.JLabel programNazwa2;
    private javax.swing.JLabel programNazwa3;
    private javax.swing.JLabel programNazwa4;
    private javax.swing.JLabel programNazwa5;
    private javax.swing.JLabel programNazwa6;
    private javax.swing.JLabel programNazwa7;
    private javax.swing.JLabel programNazwa8;
    private javax.swing.JLabel programNazwa9;
    private javax.swing.JLabel programWersja;
    // End of variables declaration//GEN-END:variables
}
